plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    id 'java'
}

java {
    sourceCompatibility = libs.versions.java.get()
}

dependencies {
    implementation libs.spring.boot.starter.web
    testImplementation libs.spring.boot.starter.test
}

test {
    useJUnitPlatform()
}
