/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eugene' at '12/15/16 12:09 PM' with Gradle 3.2.1
 *
 * @author eugene, @date 12/15/16 12:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
